services:
  Viasoft.Fiscal.Core:
    custom_kv_overwrite: ["EnableEnvironmentDependentConnectionString"]

  Viasoft.TaxManagement:
    db:
      name: Viasoft_TaxManagement
      type: mssql
    version:
      unversioned: true
  
  Korp.Fiscal.DAPI:
    db:
      name: Korp_Fiscal_Dapi
      type: mssql
      
  Korp.Fiscal.DOT:
    db:
      name: Korp_Fiscal_Dot
      type: mssql      