---
self_signed_certs_directory: "{{ korp_dir_path }}/certs"
self_signed_cert_privatekey_path: "{{ self_signed_certs_directory }}/cert.key"
self_signed_cert_path: "{{ self_signed_certs_directory }}/cert.crt"
self_signed_cert_pfx_path: "{{ self_signed_certs_directory }}/cert.pfx"
