services:
    Korp.API.Gateway.Vendas:

    Korp.API.Gateway.Producao:

    Korp.API.Gateway.Pessoas:

    Korp.API.Gateway.Logistica:

    Korp.API.Gateway.Estruturaproduto:

    Korp.API.Gateway.Estoque:

    Korp.API.Gateway.Faturamento:
