---
- hosts: 127.0.0.1
  connection: local
  
  tasks:

    - name: instalação de collections
      community.general.ansible_galaxy_install:
        type: collection
        name: "{{ item }}"
      loop:
        - community.docker
