- hosts: 127.0.0.1
  connection: local
  become: false
  gather_facts: false
  vars_prompt:
    - name: "user_pass"
      prompt: "Senha do usuário administrativo"
      private: true

  tasks:
    - name: definição de senha
      ansible.builtin.set_fact:
        user_pass: "{{ user_pass }}"
      tags:
        - always

- hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root
  vars:
    ansible_become_password: "{{ user_pass }}"

  tasks:
    - name: provisioning
      block:
        - name: provisioning
          ansible.builtin.import_role:
            name: provisioning
          tags:
            - provisioning
            - default-setup

      # bloco só será executado caso ocorra algum erro
      rescue:
        - name: tratativa de erro
          ansible.builtin.import_role:
            name: finishing
            tasks_from: error
          tags:
            - always
            - default-setup

- name: setup de playbook main.yml
  ansible.builtin.import_playbook: main.yml
