---
- hosts: all
  become: true

  roles:
    - role: provisioning
      tags:
        - provisioning

- hosts: all
  become: true
  vars:
    ansible_become_password: "{{ linux_korp.password }}"
  become_user: "{{ linux_korp.user }}"

  roles:
    - role: infrastructure
      tags:
        - infrastructure

    - role: infrastructure-desktop
      tags:
        - infrastructure-desktop

    - role: infrastructure-web
      tags:
        - infrastructure-web
