---
- hosts: all
  become: true
  # usar usuário korp(talvez)

  roles:
  - role:
    - provisioning
    tags:
      - provisioning

  tasks:
    - name: debug
      debug:
      msg:
        - "{{ mssql.address }}"
        - "{{ mssql.default_user }}"
        - "{{ linux_korp.password }}"

  #   - name: criação de usuário de uso da korp
  #     ansible.builtin.user:
  #       name: "{{ korp_user_name }}"
  #       password : "{{ korp_user_password }}"
  #       comment: Korp User
  #       group: sudo
  #       create_home: false

- hosts: all
  become: true
  become_user: "{{ korp_user_name }}"
  become_password: "{{ korp_user_password }}"

  roles:
  - role:
    - infrastructure
    tags:
      - infrastructure

