---
- hosts: all
  become: true
  become_user: root

  roles:
    # - role: provisioning
    #   tags:
    #     - provisioning

  tasks:
    - name: debug
      ansible.builtin.debug:
        msg:
          - "{{ mssql.address }}"
          - "{{ mssql.default_user }}"
          - "{{ mssql.default_password }}"
          - "{{ linux_korp.password }}"

    - name: criação de usuário de uso da korp
      ansible.builtin.user:
        name: "{{ linux_korp.user }}"
        password : "{{ linux_korp.user }}"
        comment: Korp User
        group: sudo
        create_home: false

- hosts: all
  become: true
  vars:
    ansible_become_password: "{{ linux_korp.password }}"
    # ansible_become_user: "{{ linux_korp.user }}"
  become_user: "{{ linux_korp.user }}"

  roles:
    - role: infrastructure
      tags:
        - infrastructure
