- hosts: 127.0.0.1
  connection: local
  become: false
  gather_facts: false
  vars_prompt:
    - name: "user_pass"
      prompt: "Senha do usuário administrativo: "
      private: true

  tasks:
    - name: definição de senha
      ansible.builtin.set_fact:
        user_pass: "{{ user_pass }}"
      tags:
        - always

- hosts: 127.0.0.1
  connection: local
  become: true
  vars:
    ansible_become_password: "{{ user_pass }}"

  tasks:
    - name: provisioning
      block:
        - name: provisioning
          ansible.builtin.import_role:
            name: provisioning
          tags:
            - provisioning

      # bloco só será executado caso ocorra algum erro 
      rescue:
        - name: tratativa de erro
          ansible.builtin.import_role:
            name: finishing
            tasks_from: error
          tags:
            - always

- hosts: 127.0.0.1
  connection: local
  vars:
    ansible_become_password: "{{ linux_korp.password }}"
  become_user: "{{ linux_korp.user }}"
  become: true

  tasks:
    - name: execução de playbook
      block:
        - name: setup de token
          ansible.builtin.import_role:
            name: infrastructure
            tasks_from: token_setup
          tags:
            - always

        - name: infrastructure
          ansible.builtin.import_role:
            name: infrastructure
          tags:
            - infrastructure
            - always

        - name: infrastructure-web
          ansible.builtin.import_role:
            name: infrastructure-web
          tags:
            - infrastructure-web
            - always

        - name: infrastructure-desktop
          ansible.builtin.import_role:
            name: infrastructure-desktop
          tags:
            - infrastructure-desktop
            - always

        - name: engenharia
          ansible.builtin.import_role:
            name: engenharia
          tags:
            - engenharia

        - name: contabil
          ansible.builtin.import_role:
            name: contabil
          tags:
            - contabil

        - name: ERP
          ansible.builtin.import_role:
            name: ERP
          tags:
            - ERP

        - name: fiscal
          ansible.builtin.import_role:
            name: fiscal
          tags:
            - fiscal

        - name: logistica
          ansible.builtin.import_role:
            name: logistica
          tags:
            - logistica

        - name: vendas
          ansible.builtin.import_role:
            name: vendas
          tags:
            - vendas

        - name: PCRG001
          ansible.builtin.import_role:
            name: PCRG001
          tags:
            - PCRG001

        - name: PRO09
          ansible.builtin.import_role:
            name: PRO09
          tags:
            - PRO09

        - name: LOG102
          ansible.builtin.import_role:
            name: LOG102
          tags:
            - LOG102

        - name: LOG103
          ansible.builtin.import_role:
            name: LOG103
          tags:
            - LOG103

        - name: MOB02
          ansible.builtin.import_role:
            name: MOB02
          tags:
            - MOB02

        - name: VEN07_W
          ansible.builtin.import_role:
            name: VEN07_W
          tags:
            - VEN07_W

        # essa deve ser a ultima task
        - name: finishing
          ansible.builtin.import_role:
            name: finishing
          tags:
            - finishing
            - always

      # bloco só será executado caso ocorra algum erro 
      rescue:
        - name: tratativa de erro
          ansible.builtin.import_role:
            name: finishing
            tasks_from: error
          tags:
            - always
