---
- hosts: 127.0.0.1
  connection: local

  roles:
    - role: provisioning
      tags:
        - provisioning

- hosts: 127.0.0.1
  connection: local
  vars:
    ansible_become_password: "{{ linux_korp.password }}"
  become_user: "{{ linux_korp.user }}"
  become: true

# TODO https://stackoverflow.com/questions/55521078/how-to-deal-with-errors-coming-from-ansible-roles
# adicionar envio de mensagem de erro para tenantManagement
#     - name: notificação de TenantManagement
#       ansible.builtin.uri:
#         url: "{{ gateway_url }}/TenantManagement/server-deploy/token/{{ token }}"
#         method: "PUT"
#         body_format: json
#         body:
#           status: completed
#           errorMessage:
  roles:
    - role: infrastructure
      tags:
        - infrastructure

    - role: infrastructure-web
      tags:
        - infrastructure-web

    - role: infrastructure-desktop
      tags:
        - infrastructure-desktop

    - role: apontamento
      tags:
        - apontamento

    - role: picking
      tags:
        - picking

    - role: mobile
      tags:
        - mobile

    - role: finishing
      tags:
        - finishing
