---
- hosts: 127.0.0.1
  connection: local

  roles:
    - role: provisioning
      tags:
        - provisioning

- hosts: 127.0.0.1
  connection: local
  vars:
    ansible_become_password: "{{ linux_korp.password }}"
  become_user: "{{ linux_korp.user }}"

  roles:
    - role: infrastructure
      tags:
        - infrastructure

    - role: infrastructure-web
      tags:
        - infrastructure-web

    - role: infrastructure-desktop
      tags:
        - infrastructure-desktop

    - role: apontamento
      tags:
        - apontamento

    - role: picking
      tags:
        - picking

    - role: mobile
      tags:
        - mobile
