---
- hosts: all
  become: true

  roles:
    # - role: provisioning
    #   tags:
    #     - provisioning

  tasks:
    - name: debug
      ansible.builtin.debug:
        msg:
          - "{{ mssql.address }}"
          - "{{ mssql.default_user }}"
          - "{{ mssql.default_password }}"
          - "{{ ansible_become_password }}"

    - name: criação de usuário de uso da korp
      ansible.builtin.user:
        name: "{{ ansible_become_user }}"
        password : "{{ ansible_become_password }}"
        comment: Korp User
        group: sudo
        create_home: false

- hosts: all
  become: true
  become_user: "{{ ansible_become_user }}"

  roles:
    - role: infrastructure
      tags:
        - infrastructure
