---
- name: Setup main
  hosts: 127.0.0.1
  connection: local
  vars:
    ansible_become_password: "{{ linux_korp.password }}"
  become_user: "{{ linux_korp.user }}"
  become: true

  tasks:
    - name: Execução de playbook
      block:
        - name: Default setup
          ansible.builtin.import_role:
            name: infrastructure
            tasks_from: default_setup
          tags:
            - always
            - default-setup

        - name: Infrastructure
          ansible.builtin.import_role:
            name: infrastructure
          tags:
            - infrastructure
            - default-setup

        - name: Infrastructure-web
          ansible.builtin.import_role:
            name: infrastructure-web
          tags:
            - infrastructure-web
            - default-setup

        - name: Infrastructure-desktop
          ansible.builtin.import_role:
            name: infrastructure-desktop
          tags:
            - infrastructure-desktop
            - default-setup

        - name: REL01
          ansible.builtin.import_role:
            name: REL01
          tags:
            - REL01
            - default-setup

        - name: FLOW01
          ansible.builtin.import_role:
            name: FLOW01
          tags:
            - FLOW01

        - name: Engenharia
          ansible.builtin.import_role:
            name: engenharia
          tags:
            - engenharia

        - name: Contabil
          ansible.builtin.import_role:
            name: contabil
          tags:
            - contabil

        - name: ERP
          ansible.builtin.import_role:
            name: ERP
          tags:
            - ERP

        - name: Fiscal
          ansible.builtin.import_role:
            name: fiscal
          tags:
            - fiscal

        - name: Faturamento
          ansible.builtin.import_role:
            name: faturamento
          tags:
            - faturamento

        - name: Logistica
          ansible.builtin.import_role:
            name: logistica
          tags:
            - logistica

        - name: Vendas
          ansible.builtin.import_role:
            name: vendas
          tags:
            - vendas

        - name: PCRG001
          ansible.builtin.import_role:
            name: PCRG001
          tags:
            - PCRG001

        - name: PRO09
          ansible.builtin.import_role:
            name: PRO09
          tags:
            - PRO09

        - name: LOG102
          ansible.builtin.import_role:
            name: LOG102
          tags:
            - LOG102

        - name: LOG103
          ansible.builtin.import_role:
            name: LOG103
          tags:
            - LOG103

        - name: MOB02
          ansible.builtin.import_role:
            name: MOB02
          tags:
            - MOB02

        - name: VEN07_W
          ansible.builtin.import_role:
            name: VEN07_W
          tags:
            - VEN07_W

        - name: VEN26
          ansible.builtin.import_role:
            name: VEN26
          tags:
            - VEN26

        - name: Compras
          ansible.builtin.import_role:
            name: compras
          tags:
            - compras

        - name: PES00
          ansible.builtin.import_role:
            name: PES00
          tags:
            - PES00

        - name: PES01
          ansible.builtin.import_role:
            name: PES01
          tags:
            - PES01

        - name: LOG00
          ansible.builtin.import_role:
            name: LOG00
          tags:
            - LOG00

        - name: LOG01_W
          ansible.builtin.import_role:
            name: LOG01_W
          tags:
            - LOG01_W

        - name: FAT12
          ansible.builtin.import_role:
            name: FAT12
          tags:
            - FAT12

        - name: CON51_W
          ansible.builtin.import_role:
            name: CON51_W
          tags:
            - CON51_W

        - name: FIN63_W
          ansible.builtin.import_role:
            name: FIN63_W
          tags:
            - FIN63_W

        - name: Object-storage
          ansible.builtin.import_role:
            name: object-storage
          tags:
            - never
            - object-storage

        # essa deve ser a ultima task
        - name: Finishing
          ansible.builtin.import_role:
            name: finishing
          tags:
            - finishing
            - always

      # bloco só será executado caso ocorra algum erro
      rescue:
        - name: Tratativa de erro
          ansible.builtin.import_role:
            name: finishing
            tasks_from: error
          tags:
            - always
