---
- hosts: all
  become: true
  # usar usuário korp(talvez)

  roles:
    - role: provisioning
      tags:
        - provisioning

  tasks:
    - name: Print the gateway for each host when defined
      ansible.builtin.debug:
        msg:
          - "{{ mssql.address }}"
          - "{{ mssql.default_user }}"
          - "{{ mssql.default_password }}"
          - "{{ linux_korp.password }}"

  #   - name: criação de usuário de uso da korp
  #     ansible.builtin.user:
  #       name: "{{ korp_user_name }}"
  #       password : "{{ korp_user_password }}"
  #       comment: Korp User
  #       group: sudo
  #       create_home: false

- hosts: all
  become: true
  become_user: "{{ linux_korp.user }}"
  # ansible_become_password: "{{ korp_user_password }}"

  roles:
    - role: infrastructure
      tags:
        - infrastructure
