---
- hosts: 127.0.0.1
  connection: local
  vars:
    ansible_become_password: "{{ linux_korp.password }}"
  become_user: "{{ linux_korp.user }}"
  become: true

  tasks:
    - name: object-storage
      ansible.builtin.import_role:
        name: object-storage
      tags:
        - object-storage
