- hosts: "127.0.0.1"
  
  tasks:
      - name: Printando ansible facts
      - debug:
          msg: "{{ item }}"
          with_items: 
          - "{{ ansible_distribution }}"   
          - "{{ ansible_distribution_version }}" 
      