---
hosts: localhost
tasks:
- name: Coletando informações do container
  community.docker.docker_container_info:
    name: nginx
    register: result

- name: Debug informações container
  ansible.builtin.debug:
    msg: "{{result.container}}" 