---
- hosts: 127.0.0.1
  tasks:
  - name: Verificando se a versão do Linux é 22.04
    ansible.builtin.fail:
      msg: "{{ ansible_failed_result }}"
    when: ansible_distribution_version != "22.04"
    
