- name: Setup de provisioning
  hosts: 127.0.0.1
  connection: local
  become: true
  become_user: root
  vars:
    remove_versioned: true
    remove_unversioned: false
    version_without_build: "2022.2.0"
    apps_to_remove:
      - "financeiro"
  
  tasks:
    - name: 
      ansible.builtin.include_role:
        name: utils
        tasks_from: apps/remove.yml
      tags: update
      loop_control:
        loop_var: app_name
      loop: "{{ apps_to_remove }}"
  
    # - name:
    #   vars:
    #     id: "financeiro"
    #   block:
    #     - name: Checagem de compose - versionado
    #       ansible.builtin.stat:
    #         path: "{{ playbook_dir }}/roles/{{ id }}/templates/composes/{{ version_without_build }}/{{ id }}-compose.yml.j2"
    #       register: versioned_compose_result
    #       # por algum motivo, o ansible dá erro executando essa task como super user
    #       become: false

    #     - name: Checagem de compose - não versionado
    #       ansible.builtin.stat:
    #         path: "{{ playbook_dir }}/roles/{{ id }}/templates/composes/{{ id }}-compose.yml.j2"
    #       register: unversioned_compose_result
    #       # por algum motivo, o ansible dá erro executando essa task como super user
    #       become: false

    #     - name:
    #       ansible.builtin.set_fact:
    #         has_versioned_services: "{{ versioned_compose_result.stat.exists }}"
    #         has_unversioned_services: "{{ unversioned_compose_result.stat.exists }}"

    #     - name: "Garantia de registro de {{ id }}"
    #       ansible.builtin.include_role:
    #         name: utils
    #         tasks_from: services/ensure_mapping.yml
    #       vars:
    #         registered_services: "{{ lookup('file', '{{ config_dir_path }}/korp_services.yml') | from_yaml }}"
