---
- hosts: 127.0.0.1
  tasks:
    - name: Coletando informações do container
      community.docker.docker_container_info:
        name: nginx
      register: result  
      
    - name: Does container exist?
      ansible.builtin.debug:
        msg: "The container {{ 'exists' if result.exists else 'does not exist' }}"

    - name: Debug informações container
      ansible.builtin.debug:
        msg: "{{result.container}}" 