---
- hosts: 127.0.0.1
  tasks:
    - name: Coletando informações do container
      become: true 
      community.docker.docker_container_info:
        name: nginx
      register: result  

    - name: Does container exist?
      ansible.builtin.debug:
        msg: "Container  {{ 'existe' if result.exists else 'does not exist' }}"

    - name: Debug informações container
      ansible.builtin.debug:
        msg: "{{result.container['State']['Status']}}" 
    
    - name: reiniciando container nginx 
      community.docker.docker_container:
        name: nginx
        state: started
        restart: true
