- name: definição de variáveis
  set_fact:
    services: "{{ (lookup('file', 'vars/main.yml') | from_yaml)['services'] }}"

- name: adição de serviços de MOB02
  ansible.builtin.include_role:
    name: utils
    tasks_from: services/add_service
  vars:
    service_name: "{{ item.key }}"
    id: MOB02
  with_dict: "{{ services }}"
  loop_control:
    extended: true

- name: execução de query de mobile
  community.general.mssql_script:
    login_user: "{{ mssql.korp_user }}"
    login_password: "{{ mssql.korp_password }}"
    login_host: "{{ mssql.address }}"
    name: Viasoft_Authentication
    script: "{{ lookup('template', 'queries/mobile.sql.j2') | string }}"
