- name: adição de serviços de MOB02
  ansible.builtin.include_role:
    name: utils
    tasks_from: services/add_service
  vars:
    service_name: "{{ item }}"
    consul_kv: "{{ lookup('template', 'consul_kv/{{ item | lower }}.json.j2') }}"
  loop:
    - Korp.Mobile
    - Korp.Financial.Situation
    - Korp.Logistica.SaldoProdutos
    - Korp.Sales.PriceControl
    - Viasoft.Customer.Portifolio
    - Korp.Logistic.Tracking

- name: garantia da existência dos diretórios de volumes de MOB02
  ansible.builtin.include_role:
    name: utils
    tasks_from: services/ensure_volume_folder
  vars:
    volume_path: "{{ item }}"
  loop:
    - "{{ dados_docker_dir_path }}/korp-mobile/reports"

- name: configuração e transferência de arquivos de compose versionados de MOB02
  ansible.builtin.template:
    dest: "{{ versioned_compose_dir_path }}/{{ item[:-3] | basename }}"
    src: "composes/{{ version_without_build }}/{{ item | basename }}"
    owner: "{{ linux_korp.user }}"
    group: root
    mode: '0644'
  loop:
    "{{ lookup('fileglob', 'templates/composes/{{ version_without_build }}/*', wantlist=True) | select('search','.yml.j2') }}"

- name: criação e inicialização de MOB02-compose - versionado
  community.docker.docker_compose:
    project_src: "{{ versioned_compose_dir_path }}/"
    env_file: "{{ docker_env_file_path }}"
    files:
      - MOB02-compose.yml
