x-extra_hosts:
  &extra_hosts
  - "gateway.korp.com.br:172.40.0.24"

networks:
  temporal-network:
    driver: bridge
    name: temporal-network

temporal-ui:
    container_name: temporal-ui
    depends_on:
      - temporal
    environment:
      - TEMPORAL_ADDRESS=temporal:7233
      - TEMPORAL_CORS_ORIGINS=http://localhost:3000
    image: temporalio/ui:${TEMPORAL_UI_VERSION}
    restart: always
    extra_hosts: *extra_hosts
    networks:
      - temporal-network
    ports:
      - "8080:8080"

  nginx-temporal:
    container_name: nginx-temporal
    image: nginx:1.29.4
    restart: always
    extra_hosts: *extra_hosts
    ports:
      - "8081:80"
    volumes:
      - /etc/korp/configs/temporalio/nginx/nginx.conf:/etc/nginx/nginx.conf
      - /etc/korp/configs/temporalio/nginx/basic_auth_temporal_ui:/etc/nginx/.htpasswd
    networks:
      - temporal-network
    depends_on:
      - temporal-ui