services:
  - Korp.Logistica.Picking:

  - Korp.Logistica.Picking.AnaliseDeEstoque:

  - Korp.Logistica.Picking.ControlePedidos:

  - Korp.Logistica.Picking.Faturamento:

  - Korp.Logistica.Picking.OrdemProducao:

  - Korp.Faturamento.SolicitacaoDeFaturamento:
