- name: Obter token de TenantManagement
  ansible.builtin.include_role:
    name: utils 
    tasks_from: local_requests/get_service_token/main.yaml
  vars: 
    service: Viasoft.TenantManagement
    varname: tenant_management_token

- name: Definição de 'api_request_headers'
  ansible.builtin.include_role:
    name: utils
    tasks_from: local_requests/get_service_token/set_header.yaml
  vars:
    request_token: "{{ tenant_management_token }}"

- name: Obter informações da organização
  ansible.builtin.uri:
    url: "{{ frontend.endpoints.gateway_url }}/TenantManagement/environments"
    method: GET
    headers: "{{ api_request_headers }}"       
  register: result

- name: Definição de 'variáveis'
  ansible.builtin.set_fact:
    organization_environments: "{{ result['json']['items'] }}"
    env_count: "{{ result['json']['totalCount'] }}"

- name: Validação de número de ambientes
  ansible.builtin.fail:
    msg: "Número de ambientes diferente do esperado;"
  when: env_count != "1" and env_count != "2"
