- name: Definição de variáveis
  ansible.builtin.set_fact:
    services: "{{ (lookup('ansible.builtin.template', 'vars/main.yml') | from_yaml)['services'] }}"

- name: Adição de serviços de APS
  ansible.builtin.include_role:
    name: utils
    tasks_from: services/add_service
  vars:
    service_name: "{{ item.key }}"
    id: APS
  with_dict: "{{ services }}"
  loop_control:
    extended: true

- name: Adição de cliente oauth2 para Octopus.APS, client utilizado pelo ERP para chamar o APS
  ansible.builtin.include_role:
    name: utils
    tasks_from: oauth_client/add_client
  vars:
    service_name: "Octopus.APS"
    secret: "{{ services_secrets.Others.CustomOauthClients['Octopus.APS'] }}"

- name: Criação de escopos para Korp.ERP
  ansible.builtin.include_role:
    name: utils
    tasks_from: oauth_client/add_scope
  vars:
    service_name: "Octopus.APS"
    scopes:
      - Viasoft.Production.APS.DataImporting
      - Viasoft.Production.APS.Simulation
