- name: Coleta de informações do container nginx
  community.docker.docker_container_info:
    name: nginx
  register: result

  # O container pode ainda não existir, por isso a verificação.
- name: Reinício do container nginx 
  community.docker.docker_container:
    name: nginx
    state: started
    restart: true
  when: result.exists
