- name: aguarda inicialização do rabbitmq
  community.docker.docker_container_exec:
    container: rabbitmq
    command: |
      rabbitmqctl await_startup
    chdir: /
  register: result
  retries: 5
  delay: 5
  until: result is not failed

- name: lista usuários presentes no rabbitmq
  community.docker.docker_container_exec:
    container: rabbitmq
    command: |
      rabbitmqctl list_users --silent
    chdir: /
  register: rabbitmq_raw_users

- name: criação de usuário no rabbitmq
  vars:
    replaced: "{{ rabbitmq_raw_users.stdout | replace('\t', '\n') }}" # noqa no-tabs
    rabbitmq_users: "{{ replaced.split('\n') }}"
  community.docker.docker_container_exec:
    container: rabbitmq
    command: |
      rabbitmqctl add_user "{{ rabbitmq.korp_user }}" "{{ rabbitmq.korp_password }}"
    chdir: /
  when: not rabbitmq.korp_user in rabbitmq_users

- name: adição de permissões ao usuário no rabbitmq
  community.docker.docker_container_exec:
    container: rabbitmq
    command: |
      rabbitmqctl set_permissions -p / "{{ rabbitmq.korp_user }}" .* .* .*
    chdir: /

- name: adição de tags ao usuário no rabbitmq
  community.docker.docker_container_exec:
    container: rabbitmq
    command: |
      rabbitmqctl set_user_tags "{{ rabbitmq.korp_user }}" administrator
    chdir: /
