- name: Criação de diretório de configuração de sentry-relay
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ linux_korp.user }}"
    group: root
  loop:
    - "{{ config_dir_path }}/sentry-relay"
    - "{{ config_dir_path }}/sentry-relay/projects"

- name: Configuração e transferência de arquivos de configuração de sentry-relay em templates
  ansible.builtin.template:
    dest: "{{ config_dir_path }}/sentry-relay/{{ item }}"
    src: "configs/sentry-relay/{{ item }}.j2"
    owner: "{{ linux_korp.user }}"
    group: root
    mode: '0644'
  loop:
    - credentials.json
    - config.yml

- name: Configuração e transferência de arquivos de configuração de projetos de sentry-relay
  ansible.builtin.template:
    dest: "{{ config_dir_path }}/sentry-relay/projects/{{ item.project_id }}.json"
    src: "configs/sentry-relay/projects/{{ item.project_name }}.json.j2"
    owner: "{{ linux_korp.user }}"
    group: root
    mode: '0644'
  loop:
    - project_name: WebFrontend
      project_id: "{{ services_secrets.Others.SentryRelay.Projects.WebFrontend.Id }}"

- name: Configuração e transferência de arquivos de compose
  ansible.builtin.template:
    dest: "{{ compose_dir_path }}/{{ item }}"
    src: "composes/{{ item }}.j2"
    owner: "{{ linux_korp.user }}"
    group: root
    mode: '0644'
  loop:
    - infrastructure-sentry-compose.yml

- name: Criação e inicialização de infrastructure-compose
  community.docker.docker_compose:
    project_src: "{{ compose_dir_path }}/"
    env_file: "{{ docker_env_file_path }}"
    files:
      - infrastructure-sentry-compose.yml
