- name: Subir RabbitMQ nas versão
  ansible.builtin.shell:
    "docker run --name rabbitmq --hostname rabbitmq -e RABBITMQ_NODENAME=rabbitmq -e TCP_PORTS=15672,5672 -d -v {{ dados_docker_dir_path }}/{{ rabbitmq_container_name }}:/var/lib/rabbitmq rabbitmq:{{ item }}-management"
  register: new_container_raw_result

- name: Aguarda inicialização do rabbitmq
  community.docker.docker_container_exec:
    container: rabbitmq
    command: |
      rabbitmqctl await_startup
    chdir: /
  register: result
  retries: 5
  delay: 5
  until: result is not failed

- name: Obtenção de id do novo container
  ansible.builtin.set_fact:
    rabbitmq_container_id: "{{ new_container_raw_result.stdout }}"

- name: Habilitação de todas as feature flags
  community.docker.docker_container_exec:
    container: rabbitmq
    command: |
      rabbitmqctl enable_feature_flag all
    chdir: /
  register: result
  retries: 5
  delay: 5
  until: result is not failed

- name: Print de logs
  ansible.builtin.shell:
    cmd: docker logs rabbitmq
  register: logs123

- name: debug
  ansible.builtin.debug:
    var: logs123

- name: Remoção de container do RabbitMQ
  ansible.builtin.shell:
    docker rm -f {{ rabbitmq_container_id }}


