- name: Subir RabbitMQ nas versão
  ansible.builtin.shell:
    "docker run -it --rm --name rabbitmq -p 5672:5672 -p 15672:15672 -v {{ dados_docker_dir_path }}/{{ rabbitmq_container_name }}:/var/lib/rabbitmq rabbitmq:{{ item }}-management"
  register: new_container_raw_result

- name: Obtenção de id do novo container
  ansible.builtin.set_fact:
    rabbitmq_container_id: "{{ new_container_raw_result.stdout }}"

- name: Habilitar Feature Flags
  ansible.builtin.shell:
    "docker exec -d {{ rabbitmq_container_id }} bash -c 'rabbitmqctl enable_feature_flag all'"

- name: Remoção de container do RabbitMQ desatualizado
  ansible.builtin.shell:
    docker rm -f {{ rabbitmq_container_id }}


