- name: Default Setup
  block:
    - name: Requisição de informações padrões
      ansible.builtin.include_role:
        name: utils
        tasks_from: default/variables_setup.yml

    - name: Configuração de docker
      community.docker.docker_login:
        username: "korp"
        password: "korp!4518"

  # tags 'always' é necessário aqui pois usamos 'include_role'
  tags: always
