services:
  Viasoft.Compras.PlanilhasPreco:
    db:
      name: Viasoft_Compras_PlanilhasPreco
      type: postgres

  Korp.Legacy.Compras:
    db:
      name: Korp_Legacy_Compras
      type: mssql

  Korp.Compras.NotaFiscal:

  Korp.Legacy.Compras.EntradaNota:
      version:
      unversioned: true