- name: adição de serviços
  ansible.builtin.include_role:
    name: utils
    tasks_from: services/add_service
  vars:
    service_name: "{{ item }}"
    consul_kv: "{{ lookup('template', 'consul_kv/{{ item | lower }}.json.j2') }}"
  loop:
    - Korp.Logistica.Picking
    - Korp.Logistica.Picking.AnaliseDeEstoque
    - Korp.Logistica.Picking.ControlePedidos
    - Korp.Logistica.Picking.Faturamento
    - Korp.Logistica.Picking.OrdemProducao
    - Korp.Faturamento.SolicitacaoDeFaturamento

- name: configuração e transferência de arquivos de compose
  ansible.builtin.template:
    dest: "{{ korp_dir_path }}/composes/{{ item[:-3] | basename }}"
    src: "composes/{{ item | basename }}"
    owner: "{{ linux_korp.user }}"
    group: root
    mode: '0644'
  loop:
    "{{ lookup('fileglob', 'templates/composes/*', wantlist=True) | select('search','.yml.j2') }}"

- name: criação e inicialização de web-compose
  community.docker.docker_compose:
    project_src: "{{ korp_dir_path }}/composes/"
    files:
      - picking-compose.yml
