# Variáveis obrigatórias:
# - tenant_id
# - client_organization_id
# - api_request_headers (Contém token)

- name: Obter informações das unidades organizacionais
  ansible.builtin.uri:
    url: "{{ frontend.endpoints.gateway_url }}/Licensing/LicensingManagement/licensed-tenant/{{ tenant_id }}/organization-units?OrganizationId={{ client_organization_id }}"
    method: GET
    headers: "{{ api_request_headers }}"      
  register: result

- name: Definição de 'organization_units_info'
  ansible.builtin.set_fact:
    organization_units_info: "{{ result.json['items'] }}"

