# Variáveis obrigatórias:
# - tenant_id
# - api_request_headers (Contém token)

- name: Definição de 'advanced_filter' 
  set_fact:
    advanced_filter: "%7B%22condition%22%3A%22and%22%2C%22rules%22%3A%5B%7B%22field%22%3A%22identifier%22%2C%22operator%22%3A%22contains%22%2C%22type%22%3A%22string%22%2C%22value%22%3A%22{{tenant_id}}%22%7D%5D%7D"
#   decoded: advanced_filter: "{"condition":"and","rules":[{"field":"identifier","operator":"contains","type":"string","value":"{{ tenant_id }}"}]}"



- name: Definição de 'organization_info'
  ansible.builtin.set_fact: 
    organization_info: "{{ result.json['items'] }}"
