- name: Obter token de LicensingManagement
  ansible.builtin.include_role:
    name: utils 
    tasks_from: get_service_token/main.yaml
  vars: 
    service: Viasoft.Licensing.LicensingManagement
    varname: licencing_management_token

- name: Definição de 'api_request_headers'
  ansible.builtin.include_role:
    name: utils
    tasks_from: portal_requests/set_header.yaml
  vars:
    token: "{{ licencing_management_token }}"

- name: Obter informações da organização
  ansible.builtin.include_role: 
    name: utils
    tasks_from: 'portal_requests/licensing_management/get_organization.yaml' 

- name: Definição de 'client_organization_id' 
  ansible.builtin.set_fact:
    client_organization_id: "{{ organization_info[0].licensedTenantId }}"
  
- name: Obter informações das unidades organizacionais
  ansible.builtin.include_role: 
    name: utils
    tasks_from: 'portal_requests/licensing_management/get_organization_units.yaml' 

- name: Definição de 'client_organization_units_id'
  ansible.builtin.set_fact:
    client_organization_units_id: "{{ client_organization_units_id | default([]) + [item.id] }}"
  loop: "{{ organization_units_info }}"

- name: Obter informações dos ambientes
  ansible.builtin.include_role: 
    name: utils
    tasks_from: 'portal_requests/licensing_management/get_organization_environments.yaml'
  loop: "{{ client_organization_units_id }}"
  loop_control:
    loop_var: unit_id
