- name: "validação de variáveis de {{ service_name }}"
  ansible.builtin.include_role:
    name: utils
    tasks_from: services/vars_validation

- name: criação de secret
  ansible.builtin.set_fact:
    secret: "{{ 10000 | random | to_uuid | upper }}"

- name: "adição de kv de {{ service_name }} ao consul"
  community.general.consul_kv:
    # parâmetro 'cas: "0"' faz com que KV não seja alterado caso já exista
    cas: "0"
    key: "{{ service_name }}"
    # leitura de .json.j2 localizado em templates/consul_kv da role
    value: "{{ lookup('template', 'consul_kv/{{ service_name | lower }}.json.j2') | to_nice_json}}"

- name: "adição de cliente oauth2 para {{ service_name }}"
  ansible.builtin.include_role:
    name: utils
    tasks_from: oauth_client/ensure_client
  when: not service_vars.oauth_client.skip # TODO testar quando 'oauth_client' não existir

- name: "criação de bancos de dados para {{ service_name }}"
  ansible.builtin.include_role:
    name: utils
    tasks_from: "create_db/{{ service_vars.db.type }}"
  vars:
    db_name: "{{ service_vars.db.name }}"
  when: service_vars.db is defined

- name: aaaaa
  debug:
    msg: "{{ playbook_dir }}/roles/{{ id }}/templates/composes/{{ version_without_build }}/{{ id }}-compose.json.j2" 

- name: checagem de compose sem versão
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/roles/{{ id }}/templates/composes/{{ id }}-compose.json.j2"
    # path: /home/korp/roles/contabil/templates/composes/2022.1.0/contabil-compose.json.j2
  register: unversioned_compose_result

- name: checagem de compose versionado
  ansible.builtin.stat:
    path: "{{ playbook_dir }}/roles/{{ id }}/templates/composes/{{ version_without_build }}/{{ id }}-compose.json.j2"
  register: versioned_compose_result
  



- name: "configuração e transferência de arquivos de compose de {{ id }} - versionado"
  ansible.builtin.template:
    dest: "{{ versioned_compose_dir_path }}/{{ compose_name[:-3] | basename }}"
    src: "composes/{{ version_without_build }}/{{ compose_name | basename }}"
    owner: "{{ linux_korp.user }}"
    group: root
    mode: '0644'
  loop:
    "{{ lookup('fileglob', 'templates/composes/{{ version_without_build }}/*', wantlist=True) | select('search','.yml.j2') }}"
  loop_control:
    loop_var: compose_name
  when: versioned_compose_result.stat.exists

- name: "configuração e transferência de arquivos de compose de {{ id }}"
  ansible.builtin.template:
    dest: "{{ compose_dir_path }}/{{ compose_name[:-3] | basename }}"
    src: "composes/{{ compose_name | basename }}"
    owner: "{{ linux_korp.user }}"
    group: root
    mode: '0644'
  loop:
    "{{ lookup('fileglob', 'templates/composes/*', wantlist=True) | select('search','.yml.j2') }}"
  loop_control:
    loop_var: compose_name
  when: unversioned_compose_result.stat.exists

- name: "criação e inicialização de {{ id }}-compose - versionado"
  community.docker.docker_compose:
    project_src: "{{ versioned_compose_dir_path }}/"
    env_file: "{{ docker_env_file_path }}"
    files:
      - "{{ id }}-compose.yml"
  when: versioned_compose_result.stat.exists

- name: criação e inicialização de {{ id }}-compose"
  community.docker.docker_compose:
    project_src: "{{ compose_dir_path }}/"
    env_file: "{{ docker_env_file_path }}"
    files:
      - "{{ id }}-compose.yml"
  when: unversioned_compose_result.stat.exists
