# role não só deve ser utilizada em casos específicos
# UTILIZE A ROLE 'add_service'
# role usada para adicionar kv ao consul e adicionar cliente oauth
#
# parâmetros recebidos:
#   service_name
#   consul_kv
#
# para usar, chame:
#   - name: adição de serviços
#     ansible.builtin.include_role:
#       name: utils
#       tasks_from: services/manual_service_addition
#     vars:
#       service_name: service_name

- name: criação de secret
  ansible.builtin.set_fact:
    secret: "{{ 10000 | random | to_uuid | upper }}"

- name: "garantia de kv no consul para {{ service_name }}"
  ansible.builtin.include_role:
    name: utils
    tasks_from: 'consul_kv/ensure_kv'

- name: "adição de cliente oauth2 para {{ service_name }}"
  ansible.builtin.include_role:
    name: utils
    tasks_from: oauth_client/ensure_client
