- name: ""
  block:
    - name: Definição de 'apps_to_install' caso a variável 'apps' seja uma lista vazia
      block:
      - name: Obtenção de ids de aplicativos licenciados
        ansible.builtin.uri:
          url: "{{ gateway_url }}/vault/manager/server-deploy/get-licensed-apps/{{ token }}"
          status_code: 
            - 200
        register: result
        ignore_errors: true

      - name: Definição de licensed_apps_id
        ansible.builtin.set_fact:
          licensed_apps_ids: "{{ result.json.ids }}"

      - name: Obtenção de roles disponíveis
        ansible.builtin.command: ls roles
        register: result
        delegate_to: localhost

      - name: Definição de lista de roles
        ansible.builtin.set_fact:
          available_roles: "{{ result.stdout_lines }}"

      - name: Definição de 'apps_to_install'
        ansible.builtin.set_fact:
          apps_to_install: "{{ licensed_apps_ids | intersect(available_roles) }}"
      when: apps | length == 0

    - name: Definição de 'apps_to_install' caso a variável 'apps' não seja uma lista vazia
      ansible.builtin.set_fact:
        apps_to_install: "{{ apps }}"
      when: apps | length > 0
  # tags 'always' é necessário aqui pois usamos 'include_role'
  tags: always