services:
  Viasoft.Reporting.Stimulsoft:
    db:
      name: Viasoft_Reporting_Stimulsoft
      type: mssql
    oauth_client:
      skip: true

  Viasoft.Portal:
    db:
      name: Viasoft_Portal
      type: mssql
    oauth_client:
      skip: true

  Viasoft.Notification:
    db:
      name: Viasoft_Notification
      type: mssql
    oauth_client:
      skip: true

  Viasoft.TenantManagement:
    db:
      name: Viasoft_TenantManagement
      type: mssql
    oauth_client:
      skip: true

  Viasoft.Authorization:
    db:
      name: Viasoft_Authorization
      type: mssql
    oauth_client:
      skip: true

  Viasoft.Administration:
    db:
      name: Viasoft_Administration
      type: mssql
    oauth_client:
      skip: true

  Viasoft.Licensing.LicenseServer:
    oauth_client:
      skip: true

  Viasoft.Emailing.EmailTemplate:
    db:
      name: Viasoft_Emailing_EmailTemplate
      type: mssql
    oauth_client:
      skip: true

  Viasoft.Dashboard:
    db:
      name: Viasoft_Dashboard
      type: mssql
    oauth_client:
      skip: true
      
  Viasoft.UserProfile:
    db:
      name: Viasoft_UserProfile
      type: mssql
    oauth_client:
      skip: true
