# parâmetros enviados:
#
#   db_name: string
#   server_type: string (postgres/mssql)
#
# Exemplo de uso:
#
#   - name: criação de db
#     include_role:
#       name: utils
#       tasks_from: create_db
#     vars:
#       db_name: test.database
#       server_type: mssql

- name: leitura de server_type
  set_fact:
    is_mssql: "{{ true if server_type | lower  == 'mssql' else false }}"
    is_postgres: "{{ true if server_type | lower  == 'postgres' else false }}"

- name: verificação de server_type
  fail:
    msg: a string passada para server_type não é reconhecida, ela deve ser 'postgres' ou 'mssql'
  when: not (is_mssql or is_postgres)

- name: "criação de database {{ db_name }} em SQL Server"
  community.general.mssql_script:
    login_user: "{{ mssql.default_user }}"
    login_password: "{{ mssql.default_password }}"
    login_host: "{{ mssql.address }}"
    name: master
    script: "{{ lookup('template', 'templates/queries/create_db_mssql.j2') | string }}"
  when: is_mssql

- name: "criação de database {{ db_name }} em PostgreSql"
  community.postgresql.postgresql_db:
    name: "{{ db_name }}"
    owner: "{{ postgres.default_user }}"
    login_host: "{{ postgres.address }}"
    login_user: "{{ postgres.default_user }}"
    login_password: "{{ postgres.default_password }}"
  when: is_postgres
