services:
  Viasoft.Workflow.Orchestrator:
    db:
      name: Viasoft_Workflow_Orchestrator
      type: postgres
    version:
      unversioned: true
  Viasoft.Workflow.Elsa:
    db:
      name: Viasoft_Workflow_Elsa
      type: postgres
    version:
      unversioned: true
