-- Minimal IdentityServer tables that the real Viasoft.Authentication service creates at startup.
IF DB_ID('Viasoft_Authentication') IS NULL CREATE DATABASE [Viasoft_Authentication];
GO
USE [Viasoft_Authentication];
GO
IF OBJECT_ID('dbo.ApiResources') IS NULL CREATE TABLE dbo.ApiResources (Id INT IDENTITY PRIMARY KEY, Enabled BIT, Name NVARCHAR(200) UNIQUE, DisplayName NVARCHAR(400), Description NVARCHAR(1000), Created DATETIME2, Updated DATETIME2, LastAccessed DATETIME2, NonEditable BIT, ShowInDiscoveryDocument BIT);
IF OBJECT_ID('dbo.ApiScopes') IS NULL CREATE TABLE dbo.ApiScopes (Id INT IDENTITY PRIMARY KEY, Name NVARCHAR(200), DisplayName NVARCHAR(400), Description NVARCHAR(1000), Required BIT, Emphasize BIT, ShowInDiscoveryDocument BIT, Enabled BIT);
IF OBJECT_ID('dbo.Clients') IS NULL CREATE TABLE dbo.Clients (Id INT IDENTITY PRIMARY KEY, Enabled NVARCHAR(400), ClientId NVARCHAR(200) UNIQUE, ProtocolType NVARCHAR(400), RequireClientSecret NVARCHAR(400), ClientName NVARCHAR(400), Description NVARCHAR(400), ClientUri NVARCHAR(400), LogoUri NVARCHAR(400), RequireConsent NVARCHAR(400), AllowRememberConsent NVARCHAR(400), AlwaysIncludeUserClaimsInIdToken NVARCHAR(400), RequirePkce NVARCHAR(400), AllowPlainTextPkce NVARCHAR(400), AllowAccessTokensViaBrowser NVARCHAR(400), FrontChannelLogoutUri NVARCHAR(400), FrontChannelLogoutSessionRequired NVARCHAR(400), BackChannelLogoutUri NVARCHAR(400), BackChannelLogoutSessionRequired NVARCHAR(400), AllowOfflineAccess NVARCHAR(400), IdentityTokenLifetime NVARCHAR(400), AccessTokenLifetime NVARCHAR(400), AuthorizationCodeLifetime NVARCHAR(400), ConsentLifetime NVARCHAR(400), AbsoluteRefreshTokenLifetime NVARCHAR(400), SlidingRefreshTokenLifetime NVARCHAR(400), RefreshTokenUsage NVARCHAR(400), UpdateAccessTokenClaimsOnRefresh NVARCHAR(400), RefreshTokenExpiration NVARCHAR(400), AccessTokenType NVARCHAR(400), EnableLocalLogin NVARCHAR(400), IncludeJwtId NVARCHAR(400), AlwaysSendClientClaims NVARCHAR(400), ClientClaimsPrefix NVARCHAR(400), PairWiseSubjectSalt NVARCHAR(400), Created NVARCHAR(400), Updated NVARCHAR(400), LastAccessed NVARCHAR(400), UserSsoLifetime NVARCHAR(400), UserCodeType NVARCHAR(400), DeviceCodeLifetime NVARCHAR(400), NonEditable NVARCHAR(400), RequireRequestObject NVARCHAR(400));
IF OBJECT_ID('dbo.ClientGrantTypes') IS NULL CREATE TABLE dbo.ClientGrantTypes (Id INT IDENTITY PRIMARY KEY, GrantType NVARCHAR(250), ClientId INT);
IF OBJECT_ID('dbo.ClientScopes') IS NULL CREATE TABLE dbo.ClientScopes (Id INT IDENTITY PRIMARY KEY, Scope NVARCHAR(200), ClientId INT);
IF OBJECT_ID('dbo.ClientSecrets') IS NULL CREATE TABLE dbo.ClientSecrets (Id INT IDENTITY PRIMARY KEY, Description NVARCHAR(2000), Value NVARCHAR(4000), Expiration DATETIME2, Type NVARCHAR(250), Created DATETIME2, ClientId INT);
GO
