services:
  Korp.Sales.Tracking:
    db:
      name: Korp_Sales_Tracking
      type: postgres 
    version:
      unversioned: true

  Korp.Sales.Tracking.Gateway:
    version:
      unversioned: true
