services:

  Viasoft.Sales.CommercialProposal.Core:
    db:
      name: Viasoft_Sales_CommercialProposal_Core
      type: postgres

  Viasoft.Sales.CommercialProposal.Sync:
    db:
      name: Viasoft_Sales_CommercialProposal_Sync
      type: postgres 