- name: Download de chave publica
  ansible.builtin.get_url:
    url: https://packages.broadcom.com/artifactory/api/security/keypair/SaltProjectKey/public
    dest: /etc/apt/keyrings/salt-archive-keyring-2023.pgp
    mode: '0644'

- name: Configuração de repositório
  ansible.builtin.copy:
    content: 'deb [signed-by=/etc/apt/keyrings/salt-archive-keyring-2023.pgp arch=amd64] https://packages.broadcom.com/artifactory/saltproject-deb/ stable main'
    dest: /etc/apt/sources.list.d/salt.list

- name: Instalação de salt
  ansible.builtin.apt:
    name: salt-minion
    update_cache: true

- name: Configuração de salt-minion
  ansible.builtin.template:
    dest: "/etc/salt/minion.d/korp-default.conf"
    src: "configs/salt-minion.conf.j2"
    owner: "{{ linux_korp.user }}"
    group: root
    mode: '0644'
  notify: Reinicio de salt-minion

- name: Cadastro de salt-minion
  block:
    - name: Garantia de cadastro de minion no salt master
      ansible.builtin.uri:
        url: "{{ gateway_url }}/vault/manager/server-deploy/salt/register/{{ token }}"
        status_code: 
          - 200
          - 201
      changed_when: response.status == 201
      retries: 6 
      delay: 5 
      notify: Reinicio de salt-minion
      register: result
      ignore_errors: true

    - name: Validação de resultado de registro
      ansible.builtin.fail:
        msg: "Ocorreu um problema durante registro do minion: {{ result }}"
      when: result.status != 200 and result.status != 201

    - name: Teste de conexão com salt
      block:
        - name: Ping para minion
          ansible.builtin.uri:
            url: "{{ gateway_url }}/vault/manager/server-deploy/salt/test/{{ token }}"
            status_code:
              - 200
          retries: 6
          delay: 5
          register: result
          ignore_errors: true

        - name: Validação de resultado do teste
          ansible.builtin.fail:
            msg: "Ocorreu um problema durante teste de conexão com o minion: {{ result }}"
          when: result.status != 200
      when: not skip_salt_test | default(false)
