# Documentação de instalação de salt:
# https://docs.saltproject.io/salt/install-guide/en/latest/topics/bootstrap.html#install-using-the-bootstrap-script


# download de salt-minion
- name: download de bootstrap-salt
  ansible.builtin.get_url:
    url: https://bootstrap.saltproject.io
    dest: /tmp/bootstrap-salt.sh
    mode: '0555'

- name: instalação de salt-minion
  ansible.builtin.shell: /tmp/bootstrap-salt.sh

- name: configuração de salt-minion
  ansible.builtin.template:
    dest: "/etc/salt/minion.d/korp-default.conf"
    src: "configs/salt-minion.conf.j2"
    owner: "{{ linux_korp.user }}"
    group: root
    mode: '0644'
  register: copied_file

- name: reinicio de salt-minion
  ansible.builtin.service:
    name: salt-minion
    state: restarted
  when: copied_file.changed
