# Documentação de instalação de salt:
# https://docs.saltproject.io/salt/install-guide/en/latest/topics/bootstrap.html#install-using-the-bootstrap-script


# download de salt-minion
- name: Download de bootstrap-salt
  ansible.builtin.get_url:
    url: https://bootstrap.saltproject.io
    dest: /tmp/bootstrap-salt.sh
    mode: '0555'

- name: Instalação de salt-minion
  ansible.builtin.shell: /tmp/bootstrap-salt.sh

- name: Configuração de salt-minion
  ansible.builtin.template:
    dest: "/etc/salt/minion.d/korp-default.conf"
    src: "configs/salt-minion.conf.j2"
    owner: "{{ linux_korp.user }}"
    group: root
    mode: '0644'
  notify: Reinicio de salt-minion
