- name: adição de serviços de LOG102
  ansible.builtin.include_role:
    name: utils
    tasks_from: services/add_service
  vars:
    service_name: "{{ item.key }}"
    id: LOG102
  with_dict: "{{ services }}"
  loop_control:
    extended: true
