- name: adição de serviços
  ansible.builtin.include_role:
    name: utils
    tasks_from: services/add_service
  vars:
    service_name: "{{ item.key }}"
    id: <appId ou domínio>
  with_dict: "{{ role_services }}"
  loop_control:
    extended: yes
