- name: Reinicio de Docker
  ansible.builtin.service:
    name: docker
    state: reloaded

- name: Reinicio de salt-minion
  ansible.builtin.service:
    name: salt-minion
    state: restarted

- name: Reinicio de zabbix-agent2
  ansible.builtin.service:
    name: zabbix-agent2
    state: restarted
