# Variáveis requeridas
# scope
# service_name

- name: Criação de escopos para cliente
  community.general.mssql_script:
    login_user: "{{ mssql.korp_user }}"
    login_password: "{{ mssql.korp_password }}"
    login_host: "{{ mssql.address }}"
    name: "{{ authentication_db_name }}"
    script: "{{ lookup('template', 'queries/add_oauth_scope.sql.j2') | string }}"
  loop: "{{ scopes }}"
  loop_control:
    loop_var: scope