- name: Coletando informações do container
  become: true
  community.docker.docker_container_info:
    name: nginx
  register: result
  debug:
    msg: "{{result.container['State']}}"
  listen: Restart Nginx

  # O container pode ainda não existir, por isso a verificação.
- name: Reiniciando container nginx 
  become: true
  community.docker.docker_container:
    name: nginx
    state: started
    restart: true
  when: result.exists
  listen: Restart Nginx
