dependencies:
  - role: LOG102
    when: "not ((skip_log03_w_legacy_dependencies | default(false) | bool) and version_without_build == '2024.2.0')"
  - role: campos-padroes
    when: "not ((skip_log03_w_legacy_dependencies | default(false) | bool) and version_without_build == '2024.2.0')"
  - role: contabil
    when: "not ((skip_log03_w_legacy_dependencies | default(false) | bool) and version_without_build == '2024.2.0')"
  - role: logistica
    when: "not ((skip_log03_w_legacy_dependencies | default(false) | bool) and version_without_build == '2024.2.0')"
  - role: financeiro
    when: "not ((skip_log03_w_legacy_dependencies | default(false) | bool) and version_without_build == '2024.2.0')"
